// This file is auto-generated by scripts/generate-schemas.js
// Run: npm run generate-schemas

import { ModelSchema } from './model-schemas';

/**
 * Auto-generated schemas from @fal-ai/client TypeScript definitions
 */

export const GENERATED_SCHEMAS: Record<string, ModelSchema> = {
  // Schemas will be generated here
};

export function getGeneratedSchema(modelId: string): ModelSchema | null {
  return GENERATED_SCHEMAS[modelId] || null;
}
